version: '3'

services:
  mysql:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ordersDB
    ports:
      - 3306:3306
    volumes:
      - './.docker/mysqldata:/var/lib/mysql'
